password: "Scaleio123"
domain: "domain.local"
provider: "vsphere"
vagrantbox: "dummy"
vagrantboxurl: "./box/dummy.box"
version: "1.32-402.1"
os: "el6"
packagename: "EMC-ScaleIO"

vsphere:
    vcenter_host: "vcenter01.leobigfoot.com"
    custom_spec_name: "Linux"
    data_center_name: "Home"
    compute_name: "Production"
    template_name: "CentOS-6.7"
    data_store_name: "VMFS02"
    memory: "1024"
    cpu: "1"
    user: "administrator@leobigfoot.com"
    password: "Molodoi1!"

cluster:
   name: "ScaleIOTest"
   ip: "192.168.1.110"
   nodes: "tb,primary_mdm,secondary_mdm,sds4,sdc1,gui1"

tb:
   name: "tb1"
   ip: "192.168.1.111"
   device: "/home/vagrant/scaleio1"
   device_size: "100"
   sdsname: "sds1"
   role: "tb"

primary_mdm:
   name: "mdm1"
   ip: "192.168.1.112"
   role: "primary mdm"
   sdsname: "sds2"
   device: "/home/vagrant/scaleio1"
   device_size: "100"
   protection_domain: "pdomain1"
   pool: "Pool1"

secondary_mdm:
   name: "mdm2"
   ip: "192.168.1.113"
   role: "secondary mdm"
   sdsname: "sds3"
   device: "/home/vagrant/scaleio1"
   device_size: "100"
   protection_domain: "pdomain1"
   pool: "Pool1"

sds4:
   name: "sds4"
   ip: "192.168.1.114"
   role: "sds"
   device: "/home/vagrant/scaleio1"
   device_size: "100"
   protection_domain: "pdomain2"
   pool: "Pool1"

sdc1:
   name: "sdc1"
   ip: "192.168.1.115"
   role: "sdc"
   volume: "test_vol1"
   volsize: "8"
   protection_domain: "pdomain1"
   pool: "Pool1"

gui1:   
   name: "gui1"
   ip: "192.168.1.116"
   role: "gui"

